feat(demo): add alt attribute in images
valor-software/angular2-bootstrap pull request #3932
Opened 2018-03-06 14:42 UTC by tarusin

Closes #3930

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-03-06 15:20 UTC, EvilAlexei requested changes
e2e test are failed
not latest version of env

2018-03-29 09:42 UTC, valorkin commented
@tarusin please resolve conflicts

2018-03-29 14:32 UTC, tarusin commented
@valorkin @EvilAlexei 
conflicts fixed

2018-04-05 12:30 UTC, valorkin approved these changes

2018-04-05 12:30 UTC, merged